spring.application.name=tasksflow

spring.data.mongodb.uri=mongodb+srv://aryanvishwakarma1707_db_user:vpAqFWsKfFVjs0bx@cluster0.9fkjlld.mongodb.net/tasksflow?retryWrites=true&w=majority&appName=Cluster0